version: '3.8'
services:
  postgres_db:
    image: postgres:alpine
    container_name: postgres-container
    restart: always
    networks:
      - back
    environment:
      - POSTGRES_DB=product_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_pass
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: "supplier-service-app"
    networks:
      - back
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    environment:
      - DB_HOST=postgres_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres_pass
networks:
  back:
    driver: bridge
volumes:
  postgres_db:
    driver: local