server:
  port: 8080

spring:
  liquibase:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:product_db}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres_pass}
  jpa:
    show-sql: on
    database: postgresql
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:product_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres_pass}
    driver-class-name: org.postgresql.Driver
